#spring.application.name=SpringBootRestJPA1

spring:
  application:
    name: SpringBootRestJPA1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mlamarch4
    username: root
    password: root@39
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-null-for-primitives: false
debug: true

server:
  port: 5666

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
  file:
    path: logs/
    name: logs/application.log

